# -----------------------------------------------------------------------------
#                      GitHub Actions Workflow for an R Package
# -----------------------------------------------------------------------------
name: R Package Check

# TRIGGERS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        r-version: ['release', 'devel']

    # 'steps' are a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Step 3: Install all dependencies (R and system)
      # This step is now cleaner and combines your old Step 3 and 4
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Install the system library needed by the 'lbfgs' R package
          system-packages: |
            liblbfgs-dev
          # Install rcmdcheck
          extra-packages: |
            any::rcmdcheck
          # Increment cache-version to force a fresh install
          cache-version: 7 

      # Step 4: Install LaTeX for PDF documentation
      - name: Install LaTeX
        uses: r-lib/actions/setup-tinytex@v2

      # Step 5: Run the R CMD Check
      - name: Check package
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
